website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(10000))
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    admin = db.Column(db.Boolean, default=False, nullable=False)

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "mtu.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'sdjkbgdjksg'
    app.config["SQLALCHEMY_DATABASE_URI"] = f'sqlite:///{DB_NAME}'
    db.init_app(app)
    from .views import views
    from .auth import auth
    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    from .models import User, Post
    create_database(app)
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    return app

def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('CREATED DATABASE!!')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(
                password1, method='sha256'), admin=False )
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("register.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify
from flask_login import login_required, current_user
from .models import Post
from . import db
import json

views = Blueprint('views', __name__)

@views.route('/', methods=['POST', 'GET'])
def home():
    post = Post.query.all()
    return render_template("index.html", user=current_user, post=post)
    
@views.route('/admin/', methods=['GET','POST'])
@login_required
def admin():
    post = Post.query.all()
    return render_template("manage_posts.html", user=current_user, post=post)
    
@views.route('/admin/create_posts/', methods=['GET', 'POST'])
@login_required
def create_posts():
    if request.method == 'POST':
        title = request.form.get('title')
        body = request.form.get('body')

        if len(body) < 1:
            flash('Note is too short!', category='error')
        else:
            new_post = Post(data=body, title=title)
            db.session.add(new_post)
            db.session.commit()
            flash('Note added!', category='success')
    return render_template("create_posts.html")

@views.route("/delete-post",methods=['POST'])
def delete_post():
    post = json.loads(request.data)
    postId = post['postId']
    post = Post.query.get(postId)
    db.session.delete(post)
    db.session.commit()
    return jsonify({})

@views.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.filter_by(id=post_id).one()

    return render_template('showblog.html', post=post)

website/templates/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tek Sayfa Site Sablon</title>
    <link rel="stylesheet" href="assets/css/index.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</head>
<body>
    <nav id="nav">
        <a href="#img1">HOME</a>
        <a href="#color1">ABOUT</a>
        <a href="#photography">PHOTOGRAPHY</a>
        <a href="#color2">SIKIL</a>
        <a href="#img3">BLOG</a>
        <a href="#footer">CONTACT</a>
    </nav> 
    <ion-icon onclick="opennav()" class="menu-buton" name="menu-outline"></ion-icon>
    <section id="img1" class="img">
       <h1 class="header">I am gonna show you how<br> GREAT i am!!</h1>
       <a class="header_link" href="#">Portfolio</a>
   </section>
   <section id="color1" id="color1" class="color">
        <section>
            <article class="section1_article">
               <h6 class="section1_header">We don't have excuses!</h6>
               <p class="section1_content">Every one want change but no one wanna change</p>
            </article>
        </section>
        <section class="section1_container">
                <article><i id="icon1" class="material-icons">settings_ethernet</i></article>
            <article class="section1_colom">
                <p>If you are going to start go all the way other ways don't even start</p>
            </article>
                <article><i id="icon2" class="material-icons">keyboard_alt</i></article>
            <article class="section1_colom">
                <p>You have all the books all the tapes all the acces now is time to hunt!</p>
            </article>
                <article><i id="icon3" class="material-icons">dvr</i></article>
            <article class="section1_colom">
                <p>Denginiz degilim efendim dengesizim</p>
            </article>
        </section>
   </section>
   <div id="go-up"><a href="#img1" class="material-icons">north</a></div>
   <script>
    var mybutton = document.getElementById("go-up");

    window.onscroll = function() {scrollFunction()};
    function opennav() 
    {
    var x = document.getElementById("nav");
    if (x.style.width === "100%") 
    {
        x.style.width = "0%";
    }
    else 
    {
        x.style.width = "100%";
    }
    }
    function scrollFunction() {
    if (document.body.scrollTop > 50 || document.documentElement.scrollTop > 50) {
        mybutton.style.display = "block";
    } else {
        mybutton.style.display = "none";
    }
    }

    function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
    }
</script>
</body>
</html>

website/templates/create_posts.html
<!DOCTYPE html><!--Bu satırdaki kod html sayfası olduğunu belirtiyor-->
<html><!--Bu satır sayfayı başlatıyor ve dil seçilyor-->
<head><!--Bu satırda head açılıyor Görsel olmayan ayarlar burada-->
	<title>Muhammet Talha Ugurel</title><!--Bu satır site adını giriyo-->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="keywords" content="mtu,muammet talauğurel,mtuvd">
	<link rel="stylesheet" href="../../../static/assets/css/admin.css">
	<script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/29.1.0/classic/ckeditor.js"></script>
	<script src="../../assets/js/index.js"></script>
</head>
<body>
<!--nav start-->
<div class="mobil_nav" >
    <a class="btn"><i class="fas fa-bars" onclick="opennav()"></i></a>
</div>
<nav id="nav">
<ul>
<li><a href="/">Home</a></li>
</ul>
</nav>
<!--nav end-->
<!--main admin start-->
<div class="admin-wraper">
    <!--sidebar start-->
    <div class="sidebar">
        <ul>
           <li><a href="">Manage post</a></li>
           <li><a href="">Manage users</a></li>
        </ul>
    </div>
    <!--sidebar end-->
    <!--admin content start-->
    <div class="admin-content">
        <div class="buton-grup">
            <a href="/admin" class="big-btn">Manage posts</a>
        </div>
        <div class="content">
            <h2 class="page-title">Manage posts</h2>
            <form method="post">
                <div>
                    <label>Title</label>
                    <input type="text" name="title" class="text-input" />
                    <label>Post</label>
                    <div id="editor">
                        <p>Type here...</p>
                    </div>
                    <textarea name="body" class="post-input"></textarea>
                    <div>
                        <button type="submit" class="big-btn">Add post</buton>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!--admin content end-->
</div>
<!--main admin end-->
</body>
</html>

website/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tek Sayfa Site Sablon</title>
    <link rel="stylesheet" href="../static/assets/css/index.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unopkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
	<script src="../static/assets/js/index.js"></script>
</head>
<body>
    <nav id="nav">
        {% if user.is_authenticated %}
        <a href="#img1">HOME</a>
        <a href="#color1">ABOUT</a>
        <a href="#photography">PHOTOGRAPHY</a>
        <a href="#color2">SIKIL</a>
        <a href="#img3">BLOG</a>
        <a href="#footer">CONTACT</a>
        <a href="/admin">ADMIN</a>
        {% else %}
        <a href="#img1">HOME</a>
        <a href="#color1">ABOUT</a>
        <a href="#photography">PHOTOGRAPHY</a>
        <a href="#color2">SIKIL</a>
        <a href="#img3">BLOG</a>
        <a href="#footer">CONTACT</a>
        {% endif %}
    </nav> 
    <ion-icon onclick="opennav()" class="menu-buton" name="menu-outline"></ion-icon>
    <section id="img1" class="img">
       <h1 class="header">I am gonna show you how<br> GREAT i am!!</h1>
       <a class="header_link" href="#">Portfolio</a>
   </section>
   <section id="color1" id="color1" class="color">
        <section>
            <article class="section1_article">
               <h6 class="section1_header">My mottos</h6>
               <p class="section1_content">Every one want change but no one wanna change</p>
            </article>
        </section>
        <section class="section1_container">
                <article><i id="icon1" class="material-icons">settings_ethernet</i></article>
            <article class="section1_colom">
                <p>Rest in th end not in the middle</p>
            </article>
                <article><i id="icon2" class="material-icons">keyboard_alt</i></article>
            <article class="section1_colom">
                <p>If it was be easy every body would do it</p>
            </article>
                <article><i id="icon3" class="material-icons">dvr</i></article>
            <article class="section1_colom">
                <p>If you going to try go all the way</p>
            </article>
        </section>
   </section>
   <section id="photography" class="img">
            <article class="zeen">
                <a href=""><h1 class="zeen-header">The Night of</h1></a>
                <div class="cover-v">
                    <img src="../static/assets/img/zeen1.jpg" alt="">
                </div>
            </article>
            <article class="zeen">
                <a href=""><h1 class="zeen-header">Ayvalik</h1></a>
                <div class="cover-h">
                <img src="../static/assets/img/zeen2.jpg" alt="">
                </div>
            </article>
            <article class="zeen">
                <a href=""><h1 class="zeen-header">Istanlove</h1></a>
                <div class="cover-h">
                <img src="../static/assets/img/zeen3.JPG" alt="">
                </div>
            </article>
            </article>
   </section>
   <section id="color2" class="color">
       <h1>Sikils</h1>
        <section class="sikil-container">
            <article class="sikils">
                <h2>Projeler</h2>
                <p>
Kendi web sitemi sıfırdan html, css, js, bootstrap ve python flask
kullanarak programladım. Ardından kendi evimde bana ait bir server
üzerinde yayınladım <br><br>
Flutter kullanarak yks öğrencileri için bir soru gönderme ve çözme
uygulaması yazıyorum (bitmedi). <br><br>
Raspberry pi kullanarak kişisel sesli asistan projesi yaptım bunun için
snowboy, python speechrecognition gibi framework ve kütüphaneler
kullandım. <br><br>
Vehicle dynamic ekibinde çalışırken işimi kolaylaştırmak için C dili ile
çeşitli scriptler yazdım.</p>
            </article>
                <div class="bars">
                    <h2 class="sikil">Flutter</h2>
                    <div class="bar"><div class="prosess0"></div></div>
                    <h2 class="sikil">Python</h2>
                    <div class="bar"><div class="prosess1"></div></div>
                    <h2 class="sikil">C++</h2>
                    <div class="bar"><div class="prosess2"></div></div>
                    <h2 class="sikil">Web Dev</h2>
                    <div class="bar"><div class="prosess3"></div></div>
                </div>
        </section>
   </section>
   <section id="img3" class="img">
    {% for post in post[-3:] %}
       <article>
            <h1>{{post.title}}</h1>
            <p>{{post.data[:500]}}</p>
            <a href="{{ url_for('views.post', post_id=post.id) }}">devami</a>
       </article>
       {% endfor %}
   </section>
   <section id="footer">
        <article class="designer">
        <article class="logo">
            <img src="../static/assets/img/logo.png" alt="logo">
        </article>
            <p>© Created By MTU</p>
        <article class="socical-media">
            <a href="https://www.instagram.com/muhammed.talha.ugurel/"><ion-icon id="socical-icon" name="logo-instagram"></ion-icon></a>
            <a href="https://www.linkedin.com/in/muhammed-talha-u%C4%9Furel-4b96781a3/"><ion-icon id="socical-icon" name="logo-linkedin"></ion-icon></a>
            <a href="#"><ion-icon id="socical-icon" name="logo-youtube"></ion-icon></a>
        </article>
        </article>
   </section>
   <div id="go-up"><a href="#img1" class="material-icons">north</a></div>
   <script>
    var mybutton = document.getElementById("go-up");

    window.onscroll = function() {scrollFunction()};
    function opennav() 
    {
    var x = document.getElementById("nav");
    if (x.style.width === "100%") 
    {
        x.style.width = "0%";
    }
    else 
    {
        x.style.width = "100%";
    }
    }
    function scrollFunction() {
    if (document.body.scrollTop > 50 || document.documentElement.scrollTop > 50) {
        mybutton.style.display = "block";
    } else {
        mybutton.style.display = "none";
    }
    }

    function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
    }
</script>
</body>
</html>

website/templates/login.html
<!DOCTYPE html><!--Bu satırdaki kod html sayfası olduğunu belirtiyor-->
<html><!--Bu satır sayfayı başlatıyor ve dil seçilyor-->
<head><!--Bu satırda head açılıyor Görsel olmayan ayarlar burada-->
	<title>Muhammet Talha Ugurel</title><!--Bu satır site adını giriyo-->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="keywords" content="mtu,muammet talauğurel,mtuvd">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"/>
</head><!--head kapanıyor-->
<body ><!--body opened bg color inline-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MTU</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/sign-up">Register</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

<div class=" h-100 d-flex align-items-center justify-content-center ">
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form></div>
</body><!--Body kapanıyor-->
</html><!--Html kapanıyor-->

website/templates/manage_posts.html
<!DOCTYPE html><!--Bu satırdaki kod html sayfası olduğunu belirtiyor-->
<html><!--Bu satır sayfayı başlatıyor ve dil seçilyor-->
<head><!--Bu satırda head açılıyor Görsel olmayan ayarlar burada-->
	<title>Muhammet Talha Ugurel</title><!--Bu satır site adını giriyo-->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="keywords" content="mtu,muammet talauğurel,mtuvd">
	<link rel="stylesheet" href="../../../static/assets/css/admin.css">
	<script src="https://kit.fontawesome.com/a076d05399.js"></script>
	<script src="../static/assets/js/index.js"></script>
</head>
<body>
<!--nav start-->
<div class="mobil_nav" >
    <a href="#" class="logo"><img src="../static/assets/img/mtu_sd_logo.jpeg" alt="Logo"></a>
    <a class="btn"><i class="fas fa-bars" onclick="opennav()"></i></a>
</div>
<nav id="nav">
<ul>
<li><a href="index.html">Home</a></li>
</ul>
</nav>
<!--nav end-->
<!--main admin start-->
<div class="admin-wraper">
    <!--sidebar start-->
    <div class="sidebar">
        <ul>
           <li><a href="index.php">Manage post</a></li>
           <li><a href="../users/index.html">Manage users</a></li>
           <li><a href="../topics/index.html">Manage topics</a></li>
        </ul>
    </div>
    <!--sidebar end-->
    <!--admin content start-->
    <div class="admin-content">
        <div class="buton-grup">
            <a href="/admin/create_posts/" class="big-btn">Add posts</a>
        </div>
        <div class="content">
            <h2 class="page-title">Manage posts</h2>
            <table>
                <thead>
                    <th>SN</th>
                    <th>Title</th>
                    <th>Author</th>
                    <th colspan="3">Action</th>
                </thead>
                {% for post in post%}
                <tr>
                    <td>{{post.id}}</td>
                    <td>{{post.title}}</td>
                    <td>Mtu</td>
                    <td><button type="button" class="close" onclick="deletePost({{ post.id}})">delete</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <!--admin content end-->
</div>
<!--main admin end-->
</body>
</html>

website/templates/register.html
<!DOCTYPE html><!--Bu satırdaki kod html sayfası olduğunu belirtiyor-->
<html><!--Bu satır sayfayı başlatıyor ve dil seçilyor-->
<head><!--Bu satırda head açılıyor Görsel olmayan ayarlar burada-->
	<title>Muhammet Talha Ugurel</title><!--Bu satır site adını giriyo-->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="keywords" content="mtu,muammet talauğurel,mtuvd">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"/>
</head><!--head kapanıyor-->
<body ><!--body opened bg color inline-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MTU</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

<div class=" h-100 d-flex align-items-center justify-content-center ">
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form></div>
</body><!--Body kapanıyor-->
</html><!--Html kapanıyor-->

website/templates/showblog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tek Sayfa Site Sablon</title>
    <link rel="stylesheet" href="../static/assets/css/index.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unopkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
	<script src="../static/assets/js/index.js"></script>
</head>
<body>
    <nav id="nav">
        <a href="/">HOME</a>
        <a href="#footer">CONTACT</a>
    </nav> 
    <ion-icon onclick="opennav()" class="menu-buton" name="menu-outline"></ion-icon>
   <section id="img3-blog" class="img">
       <article>
            <h1>{{post.title}}</h1>
            <p>{{post.data}}</p>
       </article>
   </section>
   <section id="footer">
        <article class="designer">
        <article class="logo">
            <img src="../static/assets/img/logo.png" alt="logo">
        </article>
            <p>© Created By MTU</p>
        <article class="socical-media">
            <a href="#"><ion-icon id="socical-icon" name="logo-instagram"></ion-icon></a>
            <a href="#"><ion-icon id="socical-icon" name="logo-linkedin"></ion-icon></a>
            <a href="#"><ion-icon id="socical-icon" name="logo-youtube"></ion-icon></a>
        </article>
        </article>
   </section>
   <div id="go-up"><a href="#img1" class="material-icons">north</a></div>
   <script>
    var mybutton = document.getElementById("go-up");

    window.onscroll = function() {scrollFunction()};
    function opennav() 
    {
    var x = document.getElementById("nav");
    if (x.style.width === "100%") 
    {
        x.style.width = "0%";
    }
    else 
    {
        x.style.width = "100%";
    }
    }
    function scrollFunction() {
    if (document.body.scrollTop > 50 || document.documentElement.scrollTop > 50) {
        mybutton.style.display = "block";
    } else {
        mybutton.style.display = "none";
    }
    }

    function topFunction() {
    document.body.scrollTop = 0;
    document.documentElement.scrollTop = 0;
    }
</script>
</body>
</html>